name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for ssd1306 library.
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: "19"
          check-path: "ssd1306"
